### ISSUE TITLE
Unable to export data

### ISSUE THREAD

**Issue by seanbonner** [Safecast/covid19map#10]
In settings, attempting to select the Export All Data option returns this error:

"file_put_contents(/var/app/current/platform/storage/app/temp/20200511-AFiUfglKaJhGhhZlgOPBVPk3iYTgY7gw8M5bLdcw.csv): failed to open stream: No such file or directory"

**Comment by auspicacious** [comment]
@seanbonner Try it again, I think I have it fixed -- the `temp` directory didn't exist and the app doesn't automatically create it. Making a fix to our deployment script now.

**Comment by seanbonner** [comment]
Works now, thank you!
