### ISSUE TITLE
No clear indication of data set on post page

### ISSUE THREAD

**Issue by matschaffer** [Safecast/covid19map#8]
I was lookin at https://covid19map.safecast.org/posts/79 and noticed there's nothing that seems to identify the post as "refused testing, symptomatic" on the screen.

It's blue, so if I go back to https://covid19map.safecast.org/ I can see that it maps to that.

Seems like we should have some way to easily see the data set from the post page.

cc @seanbonner or @auspicacious incase you saw some other ushahidi examples we should maybe look at here.

**Comment by matschaffer** [comment]
Just did a little googling and found https://abaaraha.ushahidi.io/posts/598 so maybe this should be an issue against the ushahidi repo itself.

**Comment by seanbonner** [comment]
Yeah, it's not something we chose to set one way or another and probably something that would be a good enhancement to the platform. I'll close this one for now since it's out of our hands, but definitely would be good to add on the main Ushahidi repo.
